import Head from "next/head";
import Link from "next/link";

import { AnnotationIcon, GlobeAltIcon, LightningBoltIcon, ScaleIcon, PlusIcon } from "@heroicons/react/outline";
import { useState } from "react";
import { Dialog } from "@headlessui/react";

import dynamic from "next/dynamic";
import EUsertype from "../../types/enum/_common/EUsertype";
const DemoRequestForm = dynamic(() => import("../../components/forms/rolerequest"));
const Modal = dynamic(() => import("../../components/_common/modal"));

const Index = () => {
    const [showDemoForm, setShowDemoForm] = useState(false);
    const [role, setRole] = useState(EUsertype.default);
    return (
        <div>
            <Head>
                <title>DEInclusive - Verification</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="max-w-7xl mx-auto mt-10 flex gap-x-5">
                <button
                    onClick={() => {
                        setRole(EUsertype.verified);
                        setShowDemoForm(true);
                    }}
                    type="button"
                    className="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-3 py-2 text-sm font-medium leading-4 text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                >
                    Verified
                </button>
                <button
                    onClick={() => {
                        setRole(EUsertype.pro);
                        setShowDemoForm(true);
                    }}
                    type="button"
                    className="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-3 py-2 text-sm font-medium leading-4 text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                >
                    Pro
                </button>
                <button
                    onClick={() => {
                        setRole(EUsertype.blogwriter);
                        setShowDemoForm(true);
                    }}
                    type="button"
                    className="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-3 py-2 text-sm font-medium leading-4 text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                >
                    Blog Writer
                </button>
            </div>

            <Modal open={showDemoForm} setOpen={setShowDemoForm}>
                <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                    <div className="sm:flex sm:items-start">
                        <div className="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-green-100 sm:mx-0 sm:h-10 sm:w-10">
                            <PlusIcon className="h-6 w-6 text-green-600" aria-hidden="true" />
                        </div>
                        <div className="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                            <Dialog.Title as="h3" className="text-lg leading-6 font-medium text-gray-900">
                                Request Role - {role}
                            </Dialog.Title>
                            <div className="mt-2">
                                <p className="text-sm text-gray-500">Request role.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="bg-gray-50 px-4 py-3">
                    <DemoRequestForm onSuccess={() => setShowDemoForm(false)} role={role}></DemoRequestForm>
                </div>
            </Modal>
        </div>
    );
};

export default Index;

Index.layout = "main";
